package com.reqsync.reqsync_backend.srs.enums;

/**
 * Lifecycle state of a generated SRS document.
 */
public enum SrsStatus {

    /**
     * Just generated by the AI and not yet reviewed.
     */
    GENERATED,

    /**
     * Business Analyst is actively editing the document.
     */
    DRAFT,

    /**
     * Reviewed and accepted by the Business Analyst.
     */
    REVIEWED,

    /**
     * Approved by the Project Manager.
     */
    APPROVED
}
