# ==========================================
# Developer Application
# ==========================================

spring.application.name=reqsync-developer

server.port=8083


# ==========================================
# Developer Database
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/reqsync_developer_db
spring.datasource.username=postgres
spring.datasource.password=1234


# ==========================================
# JPA / Hibernate
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# Session
# ==========================================

server.servlet.session.cookie.http-only=true

server.servlet.session.cookie.secure=false

server.servlet.session.timeout=30m