spring.application.name=reqsync-auth

server.port=8082


# ===============================
# Authentication Database
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/reqsync_auth_db
spring.datasource.username=postgres
spring.datasource.password=1234


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# JWT Configuration
# ===============================

jwt.secret=ReqSyncJWTSecretKey2026ForAuthenticationSystemSecure
jwt.expiration=86400000